Riddle/Controllers/NavbarController.cs
using Microsoft.AspNet.Identity;
using Riddle.Models;
using Riddle.Models.App.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Riddle.Controllers
{
    public class NavbarController : Controller
    {
        ApplicationDbContext _db = new ApplicationDbContext();

        [ChildActionOnly]
        public ActionResult Index()
        {
            string currentUserId = User.Identity.GetUserId();
            var model = new NavbarViewModel
            {
               
                NumberOfUnreadMessages = _db.PrivateMessages
                                             .Where(p => p.ReceiverId == currentUserId && p.IsRead == false)
                                             .Count()
            };
            return PartialView("_NavbarPartial", model);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (_db != null)
            {
                _db.Dispose();
            }
        }
    }
}

Riddle/Controllers/RiddlesController.cs
using Microsoft.AspNet.Identity;
using Riddle.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Riddle.Models.App.ViewModels;
using X.PagedList;


namespace Riddle.Controllers
{

    [Authorize]
    public class RiddlesController : Controller
    {


        private ApplicationDbContext _db = new ApplicationDbContext();



        public ActionResult Index(string searchTerm = "", int page = 1)
        {
            var model = _db.Riddles.Where(r => searchTerm == "" || r.Name.StartsWith(searchTerm))
                                   .OrderByDescending(r => r.DateCreated)
                                   .Include("User")
                                   .ToPagedList(page, 10);

            if (Request.IsAjaxRequest())
            {
                return PartialView("_Riddles", model);
            }
            return View(model);
        }

        public ActionResult Autocomplete(string term = "")
        {
            var model = _db.Riddles.Where(r => r.Name.StartsWith(term))
                                   .Take(10)
                                   .OrderBy(r => r.DateCreated)
                                   .Select(r => new
                                   {
                                       label = r.Name
                                   });


            return Json(model, JsonRequestBehavior.AllowGet);
        }


        
        public ActionResult Riddle(int Id, int page = 1) // page değişkeni sadece RiddleOwner View'i için kullanılacak.
        {
            string currentUserId = User.Identity.GetUserId();
            var riddle = _db.Riddles.Where(r => r.Id == Id).Single();

            if (riddle.User.Id == User.Identity.GetUserId()) // Check whether current user created this riddle. If so, send him/her to RiddleOwner view.
            {
                var model = riddle.Questions
                                  .Select(q => new QuestionViewModel
                                  {
                                      Question = q,
                                      SolvedUserNames = from s in _db.SolvedQuestions
                                                        where s.QuestionId == q.Id
                                                        select s.User.UserName,
                                  })
                                  .ToPagedList(page, 1);
                if (Request.IsAjaxRequest())
                {
                    return PartialView("_RiddleOwner", model);
                }
                return View("RiddleOwner", model);

            }
            else
            {
                // Check if whether already rated
                bool isAlreadyRated = _db.Reviews
                                         .Any(r => r.User.Id == currentUserId && r.Riddle.Id == Id);


                int lastQuestionId = _db.Questions
                                        .Where(q => q.RiddleId == Id)
                                        .OrderByDescending(q => q.QuestionNumber)
                                        .First().Id;
                bool isRiddleCompleted = _db.SolvedQuestions
                                            .Any(s => s.QuestionId == lastQuestionId && currentUserId == s.UserId);
                if (!isRiddleCompleted)
                {
                    var lastSolvedQuestion = _db.SolvedQuestions
                                                .Where(q => q.UserId == currentUserId && q.RiddleId == Id)
                                                .OrderByDescending(q => q.QuestionNumber)
                                                .FirstOrDefault();
                    if (lastSolvedQuestion == null) // If user hasn't solved any questions, return first question
                    {
                        var model = riddle.Questions
                                          .Where(q => q.QuestionNumber == 1)
                                          .Select(q => new QuestionViewModel
                                          {
                                              IsAlreadyRated = isAlreadyRated,
                                              Question = q,
                                              SolvedUserNames = from s in _db.SolvedQuestions
                                                                where s.QuestionId == q.Id
                                                                select s.User.UserName
                                          })
                                          .Single();

                        return View(model);
                    }

                    else // return next question
                    {
                        var model = riddle.Questions
                                          .Where(q => q.QuestionNumber == lastSolvedQuestion.QuestionNumber + 1)
                                          .Select(q => new QuestionViewModel
                                          {
                                              IsAlreadyRated = isAlreadyRated,
                                              Question = q,
                                              SolvedUserNames = from s in _db.SolvedQuestions
                                                                where s.QuestionId == q.Id
                                                                select s.User.UserName
                                          })
                                          .Single();

                        return View(model);
                    }
                }
                else
                {
                    var questions = riddle.Questions
                                          .OrderBy(q => q.QuestionNumber)
                                          .Select(q => new QuestionViewModel
                                          {
                                              IsAlreadyRated = isAlreadyRated,
                                              Question = q,
                                              SolvedUserNames = from s in _db.SolvedQuestions
                                                                where s.QuestionId == q.Id
                                                                select s.User.UserName,

                                          })
                                          .ToPagedList(page, 1);
                    return View("SolvedRiddle", questions);
                }
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Riddle([Bind(Prefix ="id")]int riddleId, string answer, int questionNumber = 1) // Bu kısım ajax kullanılarak düzenlenebilir. Böylece cevap verdikten sonra sayfa yenilemesine gerek kalmaz.
        {
            var riddle = _db.Riddles.Where(r => r.Id == riddleId).Single();
            string currentUserId = User.Identity.GetUserId();
            if (riddle.User.Id == currentUserId)
            {
                var question = riddle.Questions.Where(q => q.QuestionNumber == questionNumber).SingleOrDefault();
                return View("RiddleOwner", question);
            }
            else
            {
                bool isCorrect = answer == riddle.Questions.Where(q => q.Riddle.Id == riddleId && q.QuestionNumber == questionNumber).Single().Answer;
                ViewBag.IsCorrect = isCorrect;
                ViewBag.RiddleId = riddleId;
                if (isCorrect)
                {
                    int questionId = riddle.Questions.Where(q => q.QuestionNumber == questionNumber).Single().Id;
                    _db.SolvedQuestions.Add(new Riddle.Models.SolvedQuestion
                    {
                        QuestionId = questionId,
                        UserId = User.Identity.GetUserId(),
                        QuestionNumber = questionNumber,
                        RiddleId = riddleId
                    });
                    _db.SaveChanges();
                    return PartialView("_AnswerResult");
                }
                return PartialView("_AnswerResult");
            }
        }
        
        public ActionResult Create()
        {
            return View();
        }

      
        

        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(CreateRiddleViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _db.Questions.Add(new Models.Question
                    {
                        Body = model.FirstQuestionBody,
                        Answer = model.FirstQuestionAnswer,
                        DateCreated = DateTime.Now,
                        QuestionNumber = 1,
                        Riddle = new Models.Riddle
                        {
                            Name = model.Name,
                            Description = model.Description,
                            DateCreated = DateTime.Now,
                            User = _db.Users.Find(User.Identity.GetUserId()),
                        }
                    });

                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }

                catch
                {
                    return View();
                }
            }
            return View();
        }

        public ActionResult Edit([Bind(Prefix = "Id")] int RiddleId, int page = 1)
        {
            var riddle = _db.Riddles.Where(r => r.Id == RiddleId).Single();
            if (riddle.User.Id == User.Identity.GetUserId())
            {
                var model = riddle.Questions
                                  .Select(q => new EditViewModel
                                  {
                                      RiddleId = riddle.Id,
                                      NumberOfQuestions = riddle.Questions.Count(),

Riddle/Controllers/UserController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Riddle.Models;
using Riddle.Models.App.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Riddle.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        ApplicationDbContext _db = new ApplicationDbContext();
        public new ActionResult Profile(string id)
        {
            string currentUserId = User.Identity.GetUserId();
            var store = new UserStore<Models.ApplicationUser>(_db);
            var manager = new UserManager<Models.ApplicationUser>(store);
            var user = manager.FindById(id);
            int NumberOfQuestionsSolved = _db.SolvedQuestions
                                            .Where(s => s.UserId == id)
                                            .Count();
            DateTime registrationDate = user.DateCreated;
            var model = new UserProfileViewModel
            {
                RegistrationDate = registrationDate,
                NumberOfQuestionsSolved = NumberOfQuestionsSolved,
                CurrentUserId = currentUserId,
                ShownUserName = user.UserName,
                ShownUserId = id
            };

            return View(model);
        }

        public ActionResult AutocompleteUser(string term)
        {
            var model = _db.Users
                           .Where(u => u.UserName.StartsWith(term))
                           .Take(5)
                           .Select(u => new
                           {
                               label = u.UserName
                           });
            return Json(model, JsonRequestBehavior.AllowGet);
        }
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (_db != null)
            {
                _db.Dispose();
            }
        }
    }
}

Riddle/Views/Shared/_BBCodeButtons.cshtml
@* BBCode yerleştirmek için butonlar başlangıç *@

<button type="button" class="btn btn-default BBbutton" data-riddle-bbtag="b">b</button>
<button type="button" class="btn btn-default BBbutton" data-riddle-bbtag="i">i</button>
<button type="button" class="btn btn-default BBbutton" data-riddle-bbtag="u">u</button>
<button type="button" class="btn btn-default BBbutton" data-riddle-bbtag="quote">quote</button>
<button type="button" class="btn btn-default BBbutton" data-riddle-bbtag="link">link</button>
<button type="button" class="btn btn-default BBbutton" data-riddle-bbtag="image">image</button>
<button type="button" class="btn btn-default BBbutton" data-riddle-bbtag="simage">simage</button>
<button type="button" class="btn btn-default BBbutton" data-riddle-bbtag="code">code</button>
<button type="button" class="btn btn-default BBbutton" data-riddle-bbtag="center">center</button>

@* BBCode yerleştirmek için butonlar son *@
<br />
<br />

Riddle/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Riddle</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)

</head>
<body>
    <div id="wrap">
        <div class="navbar navbar-default navbar-static-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("RIDDLE.", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    @Html.Action("Index","Navbar")
                </div>
            </div>
        </div>
        <div class="container body-content">

            @RenderBody()
            
        </div>
        <footer class="footer">

            <p class="text-center"><small>&copy; @DateTime.Now.Year Furkan</small></p>
            <p class="text-center"><small>BBCode Parser » <a href="http://codekicker.de/">CodeKicker</a> </small></p>

        </footer>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
        @RenderSection("rating", required: false)
    </div>
</body>
</html>

Riddle/Views/Shared/_NavbarPartial.cshtml
@model Riddle.Models.App.ViewModels.NavbarViewModel
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink(Riddle.Views.Home.Resources.Resources.Home, "Index", "Home")</li>
        <li>@Html.ActionLink(Riddle.Views.Home.Resources.Resources.NavbarContact, "Contact", "Home")</li>
        <li>@Html.ActionLink(Riddle.Views.Home.Resources.Resources.Riddles, "Index", "Riddles")</li>            
        <li>
            <a href="@Url.Action("Index", "PrivateMessage")">
                <span class="glyphicon glyphicon-envelope"></span> @Riddle.Views.Home.Resources.Resources.Messages
                @if (Model.NumberOfUnreadMessages != 0)
                {
                    <span class="badge" style="background-color: #f45f42;"> @Model.NumberOfUnreadMessages</span>
                }
            </a>
        </li>
    </ul>

    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
        @Html.AntiForgeryToken()

        <ul class="nav navbar-nav navbar-right">

            @if (User.Identity.IsAdminUser())
                    {
                <li><a href="@Url.Action("Index", "Admin")">@Riddle.Views.Home.Resources.Resources._NavbarPartial_AdminPanel</a></li>
            }
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-globe"></span></a>
                <ul class="dropdown-menu">


                    <li><a href="@Url.Action("ChangeLanguage", "Home", new { lang = "en" , returnUrl = HttpContext.Current.Request.Url.AbsolutePath})">EN</a></li>
                    <li><a href="@Url.Action("ChangeLanguage", "Home", new { lang = "tr" , returnUrl = HttpContext.Current.Request.Url.AbsolutePath})">TR</a></li>
                </ul>
            </li>
            <li>
                @Html.ActionLink(Riddle.Views.Home.Resources.Resources.Hello + ' ' + User.Identity.GetUserName() + "!", "Profile", "User", routeValues: new { id = User.Identity.GetUserId() }, htmlAttributes: new { title = "Manage" })
            </li>
            <li><a href="javascript:document.getElementById('logoutForm').submit()">@Riddle.Views.Home.Resources.Resources.LogOut</a></li>
        </ul>
    }
}
else
{
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink(Riddle.Views.Home.Resources.Resources.Home, "Index", "Home")</li>
        <li>@Html.ActionLink(Riddle.Views.Home.Resources.Resources.NavbarContact, "Contact", "Home")</li>
        <li>@Html.ActionLink(Riddle.Views.Home.Resources.Resources.Riddles, "Index", "Riddles")</li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-globe"></span></a>
            <ul class="dropdown-menu">
                <li><a href="@Url.Action("ChangeLanguage", "Home", new { lang = "en", returnUrl = HttpContext.Current.Request.Url.AbsolutePath })">EN</a></li>
                <li><a href="@Url.Action("ChangeLanguage", "Home", new { lang = "tr" , returnUrl = HttpContext.Current.Request.Url.AbsolutePath})">TR</a></li>
            </ul>
        </li>
        <li>@Html.ActionLink(Riddle.Views.Home.Resources.Resources.SignUp, "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
        <li>@Html.ActionLink(Riddle.Views.Home.Resources.Resources.Login, "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
    </ul>
}