Riddle/Models/App/Riddle.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNet.Identity;

namespace Riddle.Models
{
    public class Riddle
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Display(Name = "Riddles_RiddleName", ResourceType =typeof(Views.Manage.Resources.Resources))]
        public string Name { get; set; }

        [MaxLength(200)]
        [DataType(DataType.MultilineText)]

        [Display(Name = "Riddles_Description", ResourceType = typeof(Views.Manage.Resources.Resources))]
        public string Description { get; set; }
        public string UserId { get; set; }
        [Required]
        public virtual ApplicationUser User { get; set; }
        
        [Column(TypeName = "datetime2")]

        [Display(Name = "Riddles_DateCreated", ResourceType = typeof(Views.Manage.Resources.Resources))]
        public DateTime DateCreated { get; set; }

        public virtual List<Review> Reviews { get; set; }
        public virtual List<Question> Questions { get; set; }

    }


}

Riddle/Models/App/ViewModels/AddQuestionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Riddle.Models.App.ViewModels
{
    public class AddQuestionViewModel
    {
        [DataType(DataType.MultilineText)]
        [Display(Name ="Add_Question", ResourceType =typeof(Views.Question.Resources.Resources))]
        public string Body { get; set; }
        [Display(Name = "Add_Answer", ResourceType = typeof(Views.Question.Resources.Resources))]
        public string Answer { get; set; }
    }
}

Riddle/Models/App/ViewModels/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Riddle.Models.App.ViewModels
{
    public class EditViewModel
    {
        public int RiddleId { get; set; }
        public int NumberOfQuestions { get; set; }

        public int QuestionId { get; set; }

        [DataType(DataType.MultilineText)]
        [Display(Name = "Edit_Question", ResourceType =typeof(Views.Riddles.Resources.Resources))]
        [MaxLength(2000)]
        public string Body { get; set; }

        [Display(Name = "Edit_Answer", ResourceType = typeof(Views.Riddles.Resources.Resources))]
        [MaxLength(100)]
        public string Answer { get; set; }

    }
}

Riddle/Models/App/ViewModels/UsersSolvedViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Riddle.Models.App.ViewModels
{
    public class UsersSolvedViewModel
    {
        public string UserName { get; set; }
    }
}

Riddle/Controllers/QuestionController.cs
using Microsoft.AspNet.Identity;
using X.PagedList;
using Riddle.Models;
using Riddle.Models.App.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Riddle.Controllers
{
    public class QuestionController : Controller
    {
        ApplicationDbContext _db = new ApplicationDbContext();
        public ActionResult UsersSolved([Bind(Prefix = "id")]int QuestionId, int page = 1)
        {
            var model =  from u in _db.Users
                         join s in _db.SolvedQuestions on u.Id equals s.UserId
                         where s.QuestionId == QuestionId
                         orderby u.DateCreated
                         select new UsersSolvedViewModel
                         {
                             UserName = u.UserName
                         };     
                                  
            return View(model.ToPagedList(page,30));
        }

        public ActionResult Add([Bind(Prefix="id")] int RiddleId)
        {
            ViewBag.RiddleId = RiddleId;
            string ownerId = _db.Riddles
                                .Where(r => r.Id == RiddleId)
                                .Select(r => r.UserId)
                                .Single();
            if (User.Identity.GetUserId() != ownerId)
                return HttpNotFound();     
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add([Bind(Prefix ="id")] int RiddleId, AddQuestionViewModel model)
        {
            if (ModelState.IsValid)
            {
                int lastQuestionNumber = _db.Questions
                                            .Where(q => q.RiddleId == RiddleId)
                                            .OrderByDescending(q => q.QuestionNumber)
                                            .Select(q=> q.QuestionNumber)
                                            .First();
                _db.Questions
                   .Add(new Question
                   {
                       Body = model.Body,
                       Answer = model.Answer,
                       DateCreated = DateTime.Now,
                       QuestionNumber = lastQuestionNumber+1,
                       RiddleId = RiddleId

                   });
                _db.SaveChanges();
                return RedirectToAction("Edit", "Riddles", new { Id = RiddleId, page = lastQuestionNumber + 1 });
            }
            return View(model);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (_db != null)
                _db.Dispose();
        }
    }
}

Riddle/Controllers/RatingsController.cs
using Microsoft.AspNet.Identity;
using Riddle.Models;
using Riddle.Models.App.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Riddle.Controllers
{
    public class RatingsController : Controller
    {

        ApplicationDbContext _db = new ApplicationDbContext();
        public ActionResult NewRating(int Rating, int riddleId)
        {
            string userId = User.Identity.GetUserId();
            // check if already rated
            var original = _db.Reviews
                              .Where(r => r.User.Id == userId && r.Riddle.Id == riddleId)
                              .SingleOrDefault();
            if (original != null)
            {
                original.Rating = Rating;
                _db.SaveChanges();
            }
            else
            {
                _db.Reviews.Add(new Review
                {
                    Rating = Rating,
                    DateCreated = DateTime.Now,
                    RiddleId = riddleId,
                    UserId = userId
                });
                _db.SaveChanges();
            }


            var reviews = _db.Riddles
                             .Where(r => r.Id == riddleId)
                             .Single()
                             .Reviews
                             .AsEnumerable();
            var model = new RatingViewModel
            {
                Average = reviews.Average(r => r.Rating),
                Count = reviews.Count()
            };
         
            return PartialView("_Rating", model);
    }


    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (_db != null)
        {
            _db.Dispose();
        }
    }
}
}

Riddle/Controllers/RiddlesController.cs
using Microsoft.AspNet.Identity;
using Riddle.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Riddle.Models.App.ViewModels;
using X.PagedList;


namespace Riddle.Controllers
{

    [Authorize]
    public class RiddlesController : Controller
    {


        private ApplicationDbContext _db = new ApplicationDbContext();



        public ActionResult Index(string searchTerm = "", int page = 1)
        {
            var model = _db.Riddles.Where(r => searchTerm == "" || r.Name.StartsWith(searchTerm))
                                   .OrderByDescending(r => r.DateCreated)
                                   .Include("User")
                                   .ToPagedList(page, 10);

            if (Request.IsAjaxRequest())
            {
                return PartialView("_Riddles", model);
            }
            return View(model);
        }

        public ActionResult Autocomplete(string term = "")
        {
            var model = _db.Riddles.Where(r => r.Name.StartsWith(term))
                                   .Take(10)
                                   .OrderBy(r => r.DateCreated)
                                   .Select(r => new
                                   {
                                       label = r.Name
                                   });


            return Json(model, JsonRequestBehavior.AllowGet);
        }


        
        public ActionResult Riddle(int Id, int page = 1) // page değişkeni sadece RiddleOwner View'i için kullanılacak.
        {
            string currentUserId = User.Identity.GetUserId();
            var riddle = _db.Riddles.Where(r => r.Id == Id).Single();

            if (riddle.User.Id == User.Identity.GetUserId()) // Check whether current user created this riddle. If so, send him/her to RiddleOwner view.
            {
                var model = riddle.Questions
                                  .Select(q => new QuestionViewModel
                                  {
                                      Question = q,
                                      SolvedUserNames = from s in _db.SolvedQuestions
                                                        where s.QuestionId == q.Id
                                                        select s.User.UserName,
                                  })
                                  .ToPagedList(page, 1);
                if (Request.IsAjaxRequest())
                {
                    return PartialView("_RiddleOwner", model);
                }
                return View("RiddleOwner", model);

            }
            else
            {
                // Check if whether already rated
                bool isAlreadyRated = _db.Reviews
                                         .Any(r => r.User.Id == currentUserId && r.Riddle.Id == Id);


                int lastQuestionId = _db.Questions
                                        .Where(q => q.RiddleId == Id)
                                        .OrderByDescending(q => q.QuestionNumber)
                                        .First().Id;
                bool isRiddleCompleted = _db.SolvedQuestions
                                            .Any(s => s.QuestionId == lastQuestionId && currentUserId == s.UserId);
                if (!isRiddleCompleted)
                {
                    var lastSolvedQuestion = _db.SolvedQuestions
                                                .Where(q => q.UserId == currentUserId && q.RiddleId == Id)
                                                .OrderByDescending(q => q.QuestionNumber)
                                                .FirstOrDefault();
                    if (lastSolvedQuestion == null) // If user hasn't solved any questions, return first question
                    {
                        var model = riddle.Questions
                                          .Where(q => q.QuestionNumber == 1)
                                          .Select(q => new QuestionViewModel
                                          {
                                              IsAlreadyRated = isAlreadyRated,
                                              Question = q,
                                              SolvedUserNames = from s in _db.SolvedQuestions
                                                                where s.QuestionId == q.Id
                                                                select s.User.UserName
                                          })
                                          .Single();

                        return View(model);
                    }

                    else // return next question
                    {
                        var model = riddle.Questions
                                          .Where(q => q.QuestionNumber == lastSolvedQuestion.QuestionNumber + 1)
                                          .Select(q => new QuestionViewModel
                                          {
                                              IsAlreadyRated = isAlreadyRated,
                                              Question = q,
                                              SolvedUserNames = from s in _db.SolvedQuestions
                                                                where s.QuestionId == q.Id
                                                                select s.User.UserName
                                          })
                                          .Single();

                        return View(model);
                    }
                }
                else
                {
                    var questions = riddle.Questions
                                          .OrderBy(q => q.QuestionNumber)
                                          .Select(q => new QuestionViewModel
                                          {
                                              IsAlreadyRated = isAlreadyRated,
                                              Question = q,
                                              SolvedUserNames = from s in _db.SolvedQuestions
                                                                where s.QuestionId == q.Id
                                                                select s.User.UserName,

                                          })
                                          .ToPagedList(page, 1);
                    return View("SolvedRiddle", questions);
                }
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Riddle([Bind(Prefix ="id")]int riddleId, string answer, int questionNumber = 1) // Bu kısım ajax kullanılarak düzenlenebilir. Böylece cevap verdikten sonra sayfa yenilemesine gerek kalmaz.
        {
            var riddle = _db.Riddles.Where(r => r.Id == riddleId).Single();
            string currentUserId = User.Identity.GetUserId();
            if (riddle.User.Id == currentUserId)
            {
                var question = riddle.Questions.Where(q => q.QuestionNumber == questionNumber).SingleOrDefault();
                return View("RiddleOwner", question);
            }
            else
            {
                bool isCorrect = answer == riddle.Questions.Where(q => q.Riddle.Id == riddleId && q.QuestionNumber == questionNumber).Single().Answer;
                ViewBag.IsCorrect = isCorrect;
                ViewBag.RiddleId = riddleId;
                if (isCorrect)
                {
                    int questionId = riddle.Questions.Where(q => q.QuestionNumber == questionNumber).Single().Id;
                    _db.SolvedQuestions.Add(new Riddle.Models.SolvedQuestion
                    {
                        QuestionId = questionId,
                        UserId = User.Identity.GetUserId(),
                        QuestionNumber = questionNumber,
                        RiddleId = riddleId
                    });
                    _db.SaveChanges();
                    return PartialView("_AnswerResult");
                }
                return PartialView("_AnswerResult");
            }
        }
        
        public ActionResult Create()
        {
            return View();
        }

      
        

        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(CreateRiddleViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _db.Questions.Add(new Models.Question
                    {
                        Body = model.FirstQuestionBody,
                        Answer = model.FirstQuestionAnswer,
                        DateCreated = DateTime.Now,
                        QuestionNumber = 1,
                        Riddle = new Models.Riddle
                        {
                            Name = model.Name,
                            Description = model.Description,
                            DateCreated = DateTime.Now,
                            User = _db.Users.Find(User.Identity.GetUserId()),
                        }
                    });

                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }

                catch
                {
                    return View();
                }
            }
            return View();
        }

        public ActionResult Edit([Bind(Prefix = "Id")] int RiddleId, int page = 1)
        {
            var riddle = _db.Riddles.Where(r => r.Id == RiddleId).Single();
            if (riddle.User.Id == User.Identity.GetUserId())
            {
                var model = riddle.Questions
                                  .Select(q => new EditViewModel
                                  {
                                      RiddleId = riddle.Id,
                                      NumberOfQuestions = riddle.Questions.Count(),

Riddle/Views/Riddles/AddQuestion.cshtml
@model Riddle.Models.Question

@{
    ViewBag.Title = "AddQuestion";
}

<h2>AddQuestion</h2>

@using (Html.BeginForm("AddQuestion", "Riddles")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Question</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer, "", new { @class = "text-danger" })
            </div>
        </div>
        <input type="hidden" value="@ViewBag.RiddleId" />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Riddle/Views/Riddles/Create.cshtml
@model Riddle.Models.CreateRiddleViewModel
@using Riddle.Other
@using CodeKicker.BBCode
@using Riddle.Views.Riddles.Resources

@{
    ViewBag.Title = "Create";
}

<h2>@Resources.NewRiddle</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="row">
            <div class="col-xs-12 col-md-offset-2 col-md-10">
                @Html.Partial("_BBCodeButtons")
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.FirstQuestionBody, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.FirstQuestionBody, new { htmlAttributes = new { @class = "form-control", id = "questionBody" , rows=15} })
                @Html.ValidationMessageFor(m => m.FirstQuestionBody, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.FirstQuestionAnswer, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.FirstQuestionAnswer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.FirstQuestionAnswer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@Resources.Create_Create class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(Resources.Create_BackToList, "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/App/BBCodeHelper.js")
}

Riddle/Views/Riddles/Edit.cshtml
@model IPagedList<Riddle.Models.App.ViewModels.EditViewModel>
@using Riddle.Views.Riddles.Resources

@{
    ViewBag.Title = "EditRiddle";
}

<h2>@Resources.Edit_EditRiddle</h2>


@Html.ActionLink(Resources.Edit_AddNewQuestion, "Add", "Question", new { Id = Model.First().RiddleId }, new { @class = "btn btn-primary" })


@using (Html.BeginForm("Edit", "Riddles", new { Id = Model.First().RiddleId }, FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form">

        <hr />
        <div class="row">
            <div class="col-xs-12">
                @Html.Partial("_BBCodeButtons")
            </div>
        </div>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.First().Body, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.First().Body, new { htmlAttributes = new { @class = "form-control", rows = 15, id = "questionBody" } })
            @Html.ValidationMessageFor(model => model.First().Body, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.First().Answer, htmlAttributes: new { @class = "control-label" })
            <div class="row">
                <div class="col-md-2">
                    @Html.EditorFor(model => model.First().Answer, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.First().Answer, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        @Html.HiddenFor(m => m.First().QuestionId)
        @Html.HiddenFor(m => m.First().RiddleId)



        <input type="submit" value="@Resources.Edit_Save" class="btn btn-success" />
            

    </div>
}

<div class="pagedList" data-riddle-target="#riddle">
    @Html.PagedListPager(Model, page => Url.Action("Edit", new { id = Model.First().RiddleId, page }),
                                                       PagedListRenderOptions.PageNumbersOnly)
</div>



<div>
    @Html.ActionLink(Resources.Edit_BackToList, "Index")
</div>

@section scripts{

    @Scripts.Render("~/Scripts/App/BBCodeHelper.js");
}

Riddle/Views/Riddles/Index.cshtml
@model IPagedList<Riddle.Models.Riddle>
@using Riddle.Views.Riddles.Resources



@{
    ViewBag.Title = "Son eklenen Riddle'lar";
}

<h1>@Resources.Riddles</h1>

<form class="form-inline" method="get" action="@Url.Action("Index")" data-riddle-ajax="true" data-riddle-target="#riddleList">
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="input-group">
                <input type="text" name="searchTerm" class="form-control" placeholder="@Resources.RiddleName" data-riddle-autocomplete="@Url.Action("Autocomplete")" />
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span> @Resources.Search</button>
                </span>
            </div>
        </div>
    </div>
    <br />
</form>





@Html.ActionLink(Resources.CreateNew, "Create", "Riddles", null, new { @class = "btn btn-primary" })

@Html.Partial("_Riddles", Model)





@section scripts {
    @Scripts.Render("~/Scripts/App/Riddle.js")
    @Scripts.Render("~/Scripts/jquery-ui-1.12.1.min.js")
}

Riddle/Views/Riddles/Riddle.cshtml
@model Riddle.Models.App.ViewModels.QuestionViewModel
@using Riddle.Other
@using Riddle.Views.Riddles.Resources
@{
    ViewBag.Title = "Question";
}



<br />
@if (!Model.IsAlreadyRated)
{
    @Html.Partial("_RatingStars", Model)

    @section rating {
        @Scripts.Render("~/Scripts/App/Ratings.js")
        @Styles.Render("~/Content/App/Rating.css")

    }
}



@using (Html.BeginForm("Riddle", "Riddles", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Question.RiddleId)
    <input type="hidden" name="questionNumber" value="@(Model.Question.QuestionNumber)" />
    <div class="row">
        <div class="col-xs-12 col-md-8">
            <h3>@Resources.Question</h3>
            <p>@Html.Raw(CustomizedBBCodeParser.ToHtml(Model.Question.Body))</p>
            <div class="form-group">
                <div class="col-xs-12 col-md-4">
                    @Html.LabelFor(m => m.Question.Answer, new { @class = "control-label" })
                    <input type="text" name="Answer" class="form-control" required maxlength="200" />
                    <br />
                    <button type="submit" id="sendAnswer" data-riddle-target="#answerResult" class="btn btn-primary">@Resources.Send</button>
                </div>
                <div class="col-xs-12 col-md-4" id="answerResult">

                </div>
            </div>
        </div>
        <div class="col-xs-12 col-md-4">
            @Html.Partial("_UsersSolved", Model)
        </div>
    </div>

}

@section styles{
    @Styles.Render("~/Content/App/Riddle/Styles.css")
}
@section scripts{
    @Scripts.Render("~/Scripts/App/Riddles/Riddle.js");
}

Riddle/Views/Riddles/RiddleOwner.cshtml
@model IPagedList<Riddle.Models.App.ViewModels.QuestionViewModel>

@{
    ViewBag.Title = "Riddle Owner";
}
<div id="riddle">
    @Html.Partial("_RiddleOwner", Model)

</div>



@section scripts {

    @Scripts.Render("~/Scripts/App/RiddleOwner.js")
}
@section styles{
    @Styles.Render("~/Content/App/Riddle/Styles.css")
}

Riddle/Views/Riddles/SolvedRiddle.cshtml
@model IPagedList<Riddle.Models.App.ViewModels.QuestionViewModel>
@using Riddle.Other
@using Riddle.Views.Riddles.Resources
@{
    ViewBag.Title = "SolvedRiddle";
}


<br />
@if (!Model.First().IsAlreadyRated)
{
    @Html.Partial("_RatingStars", Model.First())

    @section scripts {
        @Scripts.Render("~/Scripts/App/Ratings.js")
    }

    @section rating{
        @Styles.Render("~/Content/App/Rating.css")
    }
}

   


<div id="riddle">
    <div class="row">
        <div class="col-xs-12 col-md-8">
          
                <h3>@Resources.YouCompletedThisRiddle</h3>
                <h2>@Resources.Question</h2>
                <p>@Html.Raw(CustomizedBBCodeParser.ToHtml(Model.First().Question.Body))</p>
          
            <div class="row">
                <div class="col-xs-12 col-md-4">
                    <h3>@Resources.Answer</h3>
                    <p>@Model.First().Question.Answer</p>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-md-4">
            @Html.Partial("_UsersSolved", Model.First())
        </div>
    </div>

    <div class="pagedList" data-riddle-target="#riddle">
        @Html.PagedListPager(Model, page => Url.Action("Riddle", new { id = @Model.First().Question.RiddleId, page }),
                                                       PagedListRenderOptions.PageNumbersOnly)
    </div>

</div>

@section styles{
    @Styles.Render("~/Content/App/Riddle/Styles.css")
}

Riddle/Views/Riddles/_RatingStars.cshtml
@model Riddle.Models.App.ViewModels.QuestionViewModel


<div id="rating">
    <span id="loading" style="display:none;">
        <img src="~/Content/images/ring.gif" />
    </span>
    <form method="post" action="@Url.Action("NewRating", "Ratings", new { riddleId = Model.Question.RiddleId })" data-riddle-ajax="rating" data-riddle-target="#rating">
        <span class="rating">
            <input type="radio" class="rating-input"
                   id="rating-input-1-5" name="rating" value="5" />
            <label for="rating-input-1-5" class="rating-star"></label>
            <input type="radio" class="rating-input"
                   id="rating-input-1-4" name="rating" value="4" />
            <label for="rating-input-1-4" class="rating-star"></label>
            <input type="radio" class="rating-input" value="3"
                   id="rating-input-1-3" name="rating" />
            <label for="rating-input-1-3" class="rating-star"></label>
            <input type="radio" class="rating-input" value="2"
                   id="rating-input-1-2" name="rating" />
            <label for="rating-input-1-2" class="rating-star"></label>
            <input type="radio" class="rating-input" value="1"
                   id="rating-input-1-1" name="rating" />
            <label for="rating-input-1-1" class="rating-star"></label>
        </span>
        <button type="submit" class="btn btn-success btn-xs" id="oyla">@Riddle.Views.Riddles.Resources.Resources.Rate</button>
    </form>
</div>

Riddle/Views/Riddles/_UsersSolved.cshtml
@model Riddle.Models.App.ViewModels.QuestionViewModel
@using Riddle.Views.Riddles.Resources


    <div class="panel panel-success">
        <div class="panel-heading">
            @Resources.UsersWhoSolvedThisQuestion
        </div>
        <div class="panel-body">
            <table class="table table-striped table-hover">
                <thead>
                    <tr><th>@Resources.UserName</th></tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.SolvedUserNames)
                    {
                        <tr>
                            <td>@item</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="panel-footer">
            <a href="@Url.Action("UsersSolved", "Question", new { Id = Model.Question.Id })">@Resources.ClickHereToSeeFullList</a>
        </div>
    </div>