Riddle/Controllers/PrivateMessageController.cs
using Microsoft.AspNet.Identity;
using X.PagedList;
using Riddle.Models;
using Riddle.Models.App.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Riddle.Controllers
{
    public class PrivateMessageController : Controller
    {

        ApplicationDbContext _db = new ApplicationDbContext();


        // GET: PrivateMessage
        [Authorize]
        public ActionResult Index(int page = 1) // You need group join here.
        {
            string currentUserId = User.Identity.GetUserId();
            var model = GetMessageThreads(page);

            if (Request.IsAjaxRequest())
                return PartialView("_MessageThreads", model);

            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult NewMessageThread(NewMessageThreadViewModel viewModel, int page = 1)
        {
            string currentUserId = User.Identity.GetUserId();
            string receiverId = _db.Users.Where(u => u.UserName == viewModel.Receiver).Single().Id;
            var firstMessage = new PrivateMessage
            {
                SenderId = currentUserId,
                ReceiverId = receiverId,
                Body = viewModel.MessageBody,
                IsRead = false,
                DateCreated = DateTime.Now
            };
            _db.MessageThreads.Add(new MessageThread
            {
                Messages = new List<PrivateMessage>
                {
                    firstMessage
                },
                Title = viewModel.Title,
                SenderId = currentUserId,
                ReceiverId = receiverId
            });
            _db.SaveChanges();
            if (Request.IsAjaxRequest())
            {
                var model = GetMessageThreads(page);

                return PartialView("_MessageThreads", model);
            }
            else
            {
                return RedirectToAction("Index");
            }



        }

        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult NewPrivateMessage(SendPrivateMessageViewModel pmViewModel, int page = -1)
        {
            string currentUserId = User.Identity.GetUserId();
            string currentUserName = _db.Users.Find(currentUserId).UserName;
            pmViewModel.ReceiverName = currentUserName == pmViewModel.SenderName ? pmViewModel.ReceiverName : pmViewModel.SenderName;

            if (Request.IsAjaxRequest())
            {
                _db.PrivateMessages.Add(new PrivateMessage
                {
                    Body = pmViewModel.MessageBody,
                    DateCreated = DateTime.Now,
                    IsRead = false,
                    MessageThreadId = pmViewModel.MessageThreadId,
                    ReceiverId = _db.Users.Where(u => u.UserName == pmViewModel.ReceiverName).FirstOrDefault().Id,
                    SenderId = currentUserId
                });
                _db.SaveChanges();


                var messages = _db.PrivateMessages.Where(pm => pm.MessageThreadId == pmViewModel.MessageThreadId);
                var model = GetMessageThreadMessages(messages, page);
                SetReceiverNameAndId(pmViewModel.MessageThreadId, currentUserName, model);

                ViewBag.MessageThreadId = pmViewModel.MessageThreadId;
                return PartialView("_MessageThreadMessages", model);
            }
            return HttpNotFound();
        }

        public ActionResult MessageThreadMessages(int MessageThreadId, int page = -1)
        {
            if (Request.IsAjaxRequest())
            {
                string currentUserId = User.Identity.GetUserId();
                string currentUserName = User.Identity.GetUserName();
                var messages = _db.PrivateMessages.Where(pm => pm.MessageThreadId == MessageThreadId);
                foreach (var item in messages.Where(m => m.IsRead == false && m.ReceiverId == currentUserId))
                    item.IsRead = true;
                _db.SaveChanges();
                var model = GetMessageThreadMessages(messages, page);
                SetReceiverNameAndId(MessageThreadId, currentUserName, model);


                return PartialView("_MessageThreadMessages", model);
            }
            return HttpNotFound();
        }

        private IPagedList<MessageThreadMessagesViewModel> GetMessageThreadMessages(IQueryable<PrivateMessage> messages, int page)
        {
            var nonPageListModel = from pm in messages
                                   orderby pm.DateCreated ascending
                                   let Sender = _db.Users.Where(u => u.Id == pm.SenderId).FirstOrDefault()
                                   select new MessageThreadMessagesViewModel
                                   {
                                       MessageBody = pm.Body,
                                       SenderName = Sender.UserName,
                                       SenderId = Sender.Id,
                                       ReceiverName = _db.Users.Where(u => u.Id == pm.ReceiverId).FirstOrDefault().UserName,
                                       DateCreated = pm.DateCreated
                                   };
            if (page == -1)
            {
                page = (int)Math.Ceiling(nonPageListModel.Count() / 6.0);
            }
            var model = nonPageListModel.ToPagedList(page, 6);

            return model;
        }

        private IPagedList<MessageThreadsViewModel> GetMessageThreads(int page)
        {
            string currentUserId = User.Identity.GetUserId();
            IPagedList<MessageThreadsViewModel> model = (from pm in _db.PrivateMessages.Where(p => p.ReceiverId == currentUserId || p.SenderId == currentUserId)
                                                         group pm by pm.MessageThread into pmg
                                                         let lastMessage = pmg.OrderByDescending(p => p.DateCreated).FirstOrDefault()
                                                         let lastMessageDate = lastMessage.DateCreated
                                                         let lastSenderName = _db.Users.Where(u => lastMessage.SenderId == u.Id).FirstOrDefault().UserName
                                                         let lastMessageBody = lastMessage.Body
                                                         orderby lastMessageDate descending
                                                         select new MessageThreadsViewModel
                                                         {
                                                             NumberOfUnreadMessages = pmg.Key.Messages.Count(m => m.IsRead == false && m.ReceiverId == currentUserId),
                                                             Title = pmg.Key.Title,
                                                             LastSenderName = lastSenderName,
                                                             ThreadId = pmg.Key.Id,
                                                             LastMessageDate = lastMessageDate,
                                                             LastMessageBody = lastMessageBody.Substring(0, 50)
                                                         }).ToPagedList(page, 10);

            return model;
        }

        private void SetReceiverNameAndId(int messageThreadId, string currentUserName, IPagedList<MessageThreadMessagesViewModel> model)
        {
            ViewBag.MessageThreadId = messageThreadId;
            string receiverName = currentUserName != model.First().ReceiverName ? model.First().ReceiverName : model.First().SenderName; // find the receiver name relative to the current user.
            ViewBag.ReceiverId = _db.Users.Where(u => u.UserName == receiverName).First().Id; // find the receiver id relative to the current user.
            ViewBag.ReceiverName = receiverName;
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (_db != null)
            {
                _db.Dispose();
            }
        }
    }
}

Riddle/Controllers/UserController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Riddle.Models;
using Riddle.Models.App.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Riddle.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        ApplicationDbContext _db = new ApplicationDbContext();
        public new ActionResult Profile(string id)
        {
            string currentUserId = User.Identity.GetUserId();
            var store = new UserStore<Models.ApplicationUser>(_db);
            var manager = new UserManager<Models.ApplicationUser>(store);
            var user = manager.FindById(id);
            int NumberOfQuestionsSolved = _db.SolvedQuestions
                                            .Where(s => s.UserId == id)
                                            .Count();
            DateTime registrationDate = user.DateCreated;
            var model = new UserProfileViewModel
            {
                RegistrationDate = registrationDate,
                NumberOfQuestionsSolved = NumberOfQuestionsSolved,
                CurrentUserId = currentUserId,
                ShownUserName = user.UserName,
                ShownUserId = id
            };

            return View(model);
        }

        public ActionResult AutocompleteUser(string term)
        {
            var model = _db.Users
                           .Where(u => u.UserName.StartsWith(term))
                           .Take(5)
                           .Select(u => new
                           {
                               label = u.UserName
                           });
            return Json(model, JsonRequestBehavior.AllowGet);
        }
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (_db != null)
            {
                _db.Dispose();
            }
        }
    }
}

Riddle/Views/User/Profile.cshtml
@model Riddle.Models.App.ViewModels.UserProfileViewModel
@using Riddle.Views.User.Resources


@{
    ViewBag.Title = "Index";
}


<div class="row">
    <div class="col-md-4">
        <h2>@Model.ShownUserName</h2>
        <div class="well">
            <b>@Resources.NumberOfQuestionsSolved: </b> @Model.NumberOfQuestionsSolved<br /><br />
            <b>@Resources.JoinDate: </b> @Model.RegistrationDate <br /><br />
            @if (Model.ShownUserId == Model.CurrentUserId)
            {
                <a href="@Url.Action("Index", "Manage")">@Resources.AccountSettings</a>
            }
            else
            {
                <button type="button" class="btn btn-sm btn-success" data-toggle="modal" data-target="#myModal">
                    <span class="glyphicon glyphicon-envelope"></span> @Resources.SendNewMessage
                </button>
                <!-- Modal -->
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title" id="myModalLabel">@Riddle.Views.PrivateMessage.Resources.Resources.NewMessage</h4>
                            </div>
                            <div class="modal-body">

                                <form id="newMessageForm" action="@Url.Action("NewMessageThread","PrivateMessage")" method="get" data-riddle-ajax-target="#messageThreads">
                                    @*Model Form*@
                                    <div class="form-group">
                                        <label for="Receiver">@Riddle.Views.PrivateMessage.Resources.Resources.Receiver</label>
                                        <input type="text" class="form-control col-sm-6" name="Receiver" value="@Model.ShownUserName" id="Receiver" data-riddle-autocomplete="@Url.Action("AutocompleteUser","User")" />

                                    </div>
                                    <div class="form-group">
                                        <label for="Title">@Riddle.Views.PrivateMessage.Resources.Resources.Title</label>
                                        <input type="text" class="form-control" name="Title" id="Title" />
                                    </div>
                                    @Html.Partial("_BBCodeButtons")
                                    <div class="form-group">
                                        <label for="MessageBody" class="sr-only">Your message</label>
                                        <textarea rows="10" placeholder="Mesaj" class="form-control" id="MessageBody" , name="MessageBody"></textarea>
                                    </div>

                                </form> @*Model Form end*@
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">@Riddle.Views.PrivateMessage.Resources.Resources.Close</button>
                                <button type="button" id="sendButton" class="btn btn-primary" data-formToSend="#newMessageForm">@Riddle.Views.PrivateMessage.Resources.Resources.Send</button>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section scripts{
    @Scripts.Render("~/Scripts/App/User/Profile.js")
}